---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AdrianoMarra/spring-microservices-config-files
          searchPaths: /
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001